In [1]:
import numpy as np
import pandas as pd

In [2]:
#series
marks = pd.Series([10,20,30],index=["python","DSA","dbms"])
marks

python    10
DSA       20
dbms      30
dtype: int64

In [3]:
marks.keys()

Index(['python', 'DSA', 'dbms'], dtype='object')

In [4]:
marks.values

array([10, 20, 30], dtype=int64)

In [6]:
pd.Series(["Sakshi shah","sakshi15@gmail.com","vadodara"],["sname","mail","add"])

sname           Sakshi shah
mail     sakshi15@gmail.com
add                vadodara
dtype: object

In [7]:
my_dict = {'sname':['sakshi','het'],
           'mail': ['sakshi15@gmail.com','het02@gmail.com'],
           'add' : ['rajasthan','vadodara']}
pd.Series(my_dict)

sname                            [sakshi, het]
mail     [sakshi15@gmail.com, het02@gmail.com]
add                      [rajasthan, vadodara]
dtype: object

In [9]:
#dataframe #data,index=[],columns={}
np.random.seed(1) #lock the values 

mat = np.random.randint(0,100,(5,5))
print(mat)
result = pd.DataFrame(mat,['sakshi','het','vrund','dweeti','harshit'],['python','dsa','dbms','ooad','stb'])
result

[[37 12 72  9 75]
 [ 5 79 64 16  1]
 [76 71  6 25 50]
 [20 18 84 11 28]
 [29 14 50 68 87]]


python  dsa  dbms  ooad  stb
sakshi       37   12    72     9   75
het           5   79    64    16    1
vrund        76   71     6    25   50
dweeti       20   18    84    11   28
harshit      29   14    50    68   87

In [10]:
mat

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87]])

In [11]:
#for multiple columns, double square brackets
result [['python','dsa']]

python  dsa
sakshi       37   12
het           5   79
vrund        76   71
dweeti       20   18
harshit      29   14

In [12]:
result.loc[['het','vrund']]

python  dsa  dbms  ooad  stb
het         5   79    64    16    1
vrund      76   71     6    25   50

In [13]:
result['total']=result['python']+result['dsa']+result['dbms']+result['ooad']+result['stb']
result['percentage'] = result['total']/5 
result

python  dsa  dbms  ooad  stb  total  percentage
sakshi       37   12    72     9   75    205        41.0
het           5   79    64    16    1    165        33.0
vrund        76   71     6    25   50    228        45.6
dweeti       20   18    84    11   28    161        32.2
harshit      29   14    50    68   87    248        49.6

In [14]:
result.describe() 

python        dsa       dbms       ooad       stb       total  \
count   5.000000   5.000000   5.000000   5.000000   5.00000    5.000000   
mean   33.400000  38.800000  55.200000  25.800000  48.20000  201.400000   
std    26.613906  33.237028  30.152943  24.386472  34.86689   38.240031   
min     5.000000  12.000000   6.000000   9.000000   1.00000  161.000000   
25%    20.000000  14.000000  50.000000  11.000000  28.00000  165.000000   
50%    29.000000  18.000000  64.000000  16.000000  50.00000  205.000000   
75%    37.000000  71.000000  72.000000  25.000000  75.00000  228.000000   
max    76.000000  79.000000  84.000000  68.000000  87.00000  248.000000   

       percentage  
count    5.000000  
mean    40.280000  
std      7.648006  
min     32.200000  
25%     33.000000  
50%     41.000000  
75%     45.600000  
max     49.600000

In [15]:
result.head()

python  dsa  dbms  ooad  stb  total  percentage
sakshi       37   12    72     9   75    205        41.0
het           5   79    64    16    1    165        33.0
vrund        76   71     6    25   50    228        45.6
dweeti       20   18    84    11   28    161        32.2
harshit      29   14    50    68   87    248        49.6

In [16]:
result.head(2)

python  dsa  dbms  ooad  stb  total  percentage
sakshi      37   12    72     9   75    205        41.0
het          5   79    64    16    1    165        33.0

In [17]:
result.tail()

python  dsa  dbms  ooad  stb  total  percentage
sakshi       37   12    72     9   75    205        41.0
het           5   79    64    16    1    165        33.0
vrund        76   71     6    25   50    228        45.6
dweeti       20   18    84    11   28    161        32.2
harshit      29   14    50    68   87    248        49.6

In [18]:
result.tail(3)

python  dsa  dbms  ooad  stb  total  percentage
vrund        76   71     6    25   50    228        45.6
dweeti       20   18    84    11   28    161        32.2
harshit      29   14    50    68   87    248        49.6

In [19]:
result.iloc[3]

python         20.0
dsa            18.0
dbms           84.0
ooad           11.0
stb            28.0
total         161.0
percentage     32.2
Name: dweeti, dtype: float64

In [21]:
# Task1
# Question 1
pname = ['abc','def','ghi','jkl','mno']
pid = [1,2,3,4,5]
pprice = [100,200,300,350,400]


demo = pd.DataFrame((pname,pid,pprice),['name','id','price'])
demo

0    1    2    3    4
name   abc  def  ghi  jkl  mno
id       1    2    3    4    5
price  100  200  300  350  400

In [22]:
#Question 2
demo[0]

name     abc
id         1
price    100
Name: 0, dtype: object

In [23]:
demo[1]

name     def
id         2
price    200
Name: 1, dtype: object

In [24]:
demo[2]

name     ghi
id         3
price    300
Name: 2, dtype: object

In [25]:
demo[3]

name     jkl
id         4
price    350
Name: 3, dtype: object

In [26]:
demo[4]

name     mno
id         5
price    400
Name: 4, dtype: object

In [27]:
#Question 3
demo.loc[['id','name','price']]

0    1    2    3    4
id       1    2    3    4    5
name   abc  def  ghi  jkl  mno
price  100  200  300  350  400

In [28]:
demo.iloc[2]

0    100
1    200
2    300
3    350
4    400
Name: price, dtype: object

In [29]:
#Question 4
demo.loc['name']

0    abc
1    def
2    ghi
3    jkl
4    mno
Name: name, dtype: object

In [30]:
demo.iloc[1:4]

0    1    2    3    4
id       1    2    3    4    5
price  100  200  300  350  400

In [31]:
#Question 5
demo.iloc[1:3]

0    1    2    3    4
id       1    2    3    4    5
price  100  200  300  350  400

In [32]:
np.random.seed(1) #lock the values 
mat = np.random.randint(0,100,(5,5))
temp = pd.DataFrame(mat,['sakshi','het','vrund','dweeti','harshit'],['python','dsa','dbms','ooad','stb'])
temp.sum()/5

python    33.4
dsa       38.8
dbms      55.2
ooad      25.8
stb       48.2
dtype: float64

In [33]:
# Question 8 
temp.loc[temp['python']<40, 'python'] = 41
temp

python  dsa  dbms  ooad  stb
sakshi       41   12    72     9   75
het          41   79    64    16    1
vrund        76   71     6    25   50
dweeti       41   18    84    11   28
harshit      41   14    50    68   87

In [34]:
#Question 9
temp = temp + 20
temp

python  dsa  dbms  ooad  stb
sakshi       61   32    92    29   95
het          61   99    84    36   21
vrund        96   91    26    45   70
dweeti       61   38   104    31   48
harshit      61   34    70    88  107

In [35]:
temp[temp>100] = 100
temp

python  dsa  dbms  ooad  stb
sakshi       61   32    92    29   95
het          61   99    84    36   21
vrund        96   91    26    45   70
dweeti       61   38   100    31   48
harshit      61   34    70    88  100

In [36]:
#Question 10
temp[(temp['python']>50) & (temp['dsa']>60)]

python  dsa  dbms  ooad  stb
het        61   99    84    36   21
vrund      96   91    26    45   70

In [38]:
#Question 11
temp[temp.index.str.startswith('s')]

python  dsa  dbms  ooad  stb
sakshi      61   32    92    29   95

In [39]:
#Question 12
temp[temp.index.str.endswith('i')]

python  dsa  dbms  ooad  stb
sakshi      61   32    92    29   95
dweeti      61   38   100    31   48

In [40]:
#Question 13
print(temp.sum())
temp.sum()/5

python    340
dsa       294
dbms      372
ooad      229
stb       334
dtype: int64


python    68.0
dsa       58.8
dbms      74.4
ooad      45.8
stb       66.8
dtype: float64

In [41]:
#Question 14 
result['result'] = np.where(result['percentage']<35,'fail','pass')
result

python  dsa  dbms  ooad  stb  total  percentage result
sakshi       37   12    72     9   75    205        41.0   pass
het           5   79    64    16    1    165        33.0   fail
vrund        76   71     6    25   50    228        45.6   pass
dweeti       20   18    84    11   28    161        32.2   fail
harshit      29   14    50    68   87    248        49.6   pass

In [42]:
#Question 16
result.describe()

python        dsa       dbms       ooad       stb       total  \
count   5.000000   5.000000   5.000000   5.000000   5.00000    5.000000   
mean   33.400000  38.800000  55.200000  25.800000  48.20000  201.400000   
std    26.613906  33.237028  30.152943  24.386472  34.86689   38.240031   
min     5.000000  12.000000   6.000000   9.000000   1.00000  161.000000   
25%    20.000000  14.000000  50.000000  11.000000  28.00000  165.000000   
50%    29.000000  18.000000  64.000000  16.000000  50.00000  205.000000   
75%    37.000000  71.000000  72.000000  25.000000  75.00000  228.000000   
max    76.000000  79.000000  84.000000  68.000000  87.00000  248.000000   

       percentage  
count    5.000000  
mean    40.280000  
std      7.648006  
min     32.200000  
25%     33.000000  
50%     41.000000  
75%     45.600000  
max     49.600000

In [43]:
result.to_json('result.json')

In [45]:
result.to_html('result.html')

In [46]:
# Question 17
result.dtypes

python          int32
dsa             int32
dbms            int32
ooad            int32
stb             int32
total           int32
percentage    float64
result         object
dtype: object

In [47]:
# Question 18
result.to_dict (orient = 'list')

{'python': [37, 5, 76, 20, 29],
 'dsa': [12, 79, 71, 18, 14],
 'dbms': [72, 64, 6, 84, 50],
 'ooad': [9, 16, 25, 11, 68],
 'stb': [75, 1, 50, 28, 87],
 'total': [205, 165, 228, 161, 248],
 'percentage': [41.0, 33.0, 45.6, 32.2, 49.6],
 'result': ['pass', 'fail', 'pass', 'fail', 'pass']}